### ISSUE TITLE
`sum` operation not correct on flat HexGrid

### ISSUE THREAD

**Issue by tmillenaar** [tmillenaar/GridKit#34]
The following example errors with a numpy broadcast error:

```
import gridkit

hexdem = gridkit.HexGrid(size=3, shape="flat")

path_dem = "tests/data/alps_dem.tiff"

dem1 = gridkit.read_raster(path_dem, bounds=(29040, 167500, 29100, 167620)).resample(hexdem)
dem2 = gridkit.read_raster(path_dem, bounds=(29070, 167470, 29150, 167580)).resample(hexdem)
dem3 = gridkit.read_raster(path_dem, bounds=(29080, 167520, 29160, 167600)).resample(hexdem)

dem_slices = [dem1, dem2, dem3]

dem_sum = gridkit.sum(dem_slices)
```

This errors with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timo/Documents/projects/gridding_bare/gridkit/_statistical_functions.py", line 67, in sum
    combined_grid += empty_grid.assign(
  File "/home/timo/Documents/projects/gridding_bare/gridkit/bounded_grid.py", line 485, in assign
    crop[:] = data
ValueError: could not broadcast input array from shape (22,39) into shape (35,26)
```

It is noteworthy that the same code does work for "pointy" grids.
Likely we don't properly consider the change in consistent and offset axis.

**Comment by tmillenaar** [comment]
The incorrect slice resulting in the shape error further down is created in HexGrid._data_slice_from_bounds:
https://github.com/tmillenaar/GridKit/blob/a74b906fe96563d927341d302dcbe06898afe24a/gridkit/hex_grid.py#L752C9-L752C32

**Comment by tmillenaar** [comment]
This can be further traced back to the properties `width` and `height` not matching the underlying data.

The 'flat' HexGrid and the 'pointy' HexGrid share the same logic for most functions. The difference is often that the consistent and the offset axis are swapped. This swapping can be seen here for example: https://github.com/tmillenaar/GridKit/blob/a74b906fe96563d927341d302dcbe06898afe24a/gridkit/hex_grid.py#L959
As a result, the axis are flipped in a sense.
This means that while a RectGrid and a 'pointy' HexGrid have a data shape of [y,x] as per the numpy convention, that of a 'flat' grid is using [x,y]. This is confusing but allows us to reuse a lot of code.
As a result the 'height' and 'width' are flipped.
You will find in the following screenshot of the data that the height is 36 while the width is 29. This is flipped in the terminal:
![image](https://github.com/tmillenaar/GridKit/assets/45204355/664f8b0f-718b-48b6-82ff-d18c48c8c9b8)
![image](https://github.com/tmillenaar/GridKit/assets/45204355/265601da-5e8b-4b9c-b899-f7a822b449be)

This flip trickles down into `_data_slice_from_bounds` mentioned in the previous comment.

Note that if this swap of height and width is fixed, we still need to return slice_x, slice_y instead of slice_y, slice_x form _data_slice_from_bounds.
